Repository TeamHavit/Havit-Android, pull requests merged in 2022-08, with the labels that each got.

#655 [FEAT] 마이페이지 서버 에러처리 구현 (#654)
  app/src/main/java/org/sopt/havit/data/repository/MyPageRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/domain/repository/MyPageRepository.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/layout_network_error.xml
Labels: FEAT, NAYOUNG💜

#660 Fix/design qa
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignActivity.kt
  app/src/main/res/drawable-hdpi/img_personal_data_policy.png
  app/src/main/res/drawable-hdpi/img_policy.png
  app/src/main/res/drawable-mdpi/img_personal_data_policy.png
  app/src/main/res/drawable-mdpi/img_policy.png
  app/src/main/res/drawable-xhdpi/img_personal_data_policy.png
  app/src/main/res/drawable-xhdpi/img_policy.png
  app/src/main/res/drawable-xxhdpi/img_personal_data_policy.png
  app/src/main/res/drawable-xxhdpi/img_policy.png
  app/src/main/res/drawable-xxxhdpi/img_personal_data_policy.png
  app/src/main/res/drawable-xxxhdpi/img_policy.png
  app/src/main/res/drawable/img_privacy_policy.png
  app/src/main/res/layout/activity_category_order_modify.xml
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/activity_setting_personal_data.xml
  app/src/main/res/layout/activity_setting_policy.xml
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/layout/fragment_save.xml
  app/src/main/res/layout/layout_home_category.xml
Labels: UI, HYORIM😎

#662 Fix/design qa
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/ui/share/notification/PickerFragment.kt
  app/src/main/res/layout/fragment_picker.xml
Labels: UI, HYORIM😎

#664 [UI] 마이페이지 전체 카테고리 뒤로가기 버튼 추가 (#663)
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
Labels: UI, NAYOUNG💜

#657 [FEAT] 알림 완료 된 경우, 알림 텍스트 색 변경 및 알림 아이콘 사라짐 처리 (#656)
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/layout/item_contents_linear_min.xml
Labels: FEAT, HYEIN💛

#658 [FIX] Signup 서버 에러 이미지 추가 및 마이페이지 로직 수정(#653)
  app/src/main/java/org/sopt/havit/data/repository/MyPageRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/di/RepositoryModule.kt
  app/src/main/java/org/sopt/havit/ui/sign/AddTosFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignViewModel.kt
  app/src/main/res/layout/fragment_add_tos.xml
Labels: FIX, NAYOUNG💜

#665 Feature/share
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
  app/src/main/java/org/sopt/havit/util/HavitAuthUtil.kt
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/layout_network_error.xml
Labels: FEAT, HYORIM😎

#670 Feat/single click
  app/src/main/java/org/sopt/havit/data/RetrofitObject.kt
  app/src/main/java/org/sopt/havit/ui/share/add_category/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/util/ViewExtensions.kt
Labels: FEAT, HYORIM😎

#674 [FEAT] 컨텐츠 더보기 / 알림삭제 구현 (#673)
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreViewModel.kt
Labels: FEAT, HYORIM😎

#671 Feature/home
  app/build.gradle
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationActivity.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/java/org/sopt/havit/util/CustomDecoration.kt
  app/src/main/res/anim/rotation_refresh.xml
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/activity_service_guide.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, UI, YUBIN💙

#676 Feat/dialog
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/util/DialogUtil.kt
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎

#678 Feat/contents more
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_title/EditTitleFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_title/EditTitleFromMoreViewModel.kt
Labels: FEAT, HYORIM😎

#680 Feat/contents more
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_title/EditTitleFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/util/ToastUtil.kt
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎

#684 Fix/debug before release
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsSummeryData.kt
  app/src/main/java/org/sopt/havit/data/remote/CreateContentsRequest.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreViewModel.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/util/ImageProvider.kt
  app/src/main/java/org/sopt/havit/util/ToastUtil.kt
  app/src/main/res/layout/toast_text.xml
  app/src/main/res/values/strings.xml
Labels: FIX, HYORIM😎

#686 Fix/debug before release
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/notification/PickerFragment.kt
Labels: FIX, HYORIM😎

#688 Fix/debug before release
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/BottomSheetMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/ContentsMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
Labels: FIX, HYORIM😎

#690 Fix/debug before release
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationActivity.kt
  app/src/main/res/drawable/ic_logo_monochrome_purple.xml
Labels: UI, HYORIM😎

#692 [FEAT] Havit build type release 일 때 코드 난독화 (#691)
  app/build.gradle
  app/proguard-rules.pro
Labels: FEAT, HYORIM😎

#694 [FEAT] 환경설정 / 공유하기 notion 링크 연결 (#693)
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingNoticeActivity.kt
  app/src/main/res/layout/activity_setting_notice.xml
Labels: FEAT, HYORIM😎

#702 Feature/login
  app/src/main/java/org/sopt/havit/ui/sign/AddTosFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
  app/src/main/res/layout/activity_splash_with_sign.xml
Labels: FEAT, NAYOUNG💜

#704 Feature/search
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_title/EditTitleFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/res/layout/item_contents_search.xml
Labels: FEAT, NAYOUNG💜

#705 Feature/webview
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
Labels: FEAT, NAYOUNG💜
