Repository TeamHavit/Havit-Android, pull requests merged in 2022-01, with the labels that each got.

#3 [FIX] Fix Category UI (#2)
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_category_content_modify.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_category_modify.xml
Labels: FIX, HYEIN💛

#22 Feature/search
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/data/repository/SearchRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchFragment.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/java/org/sopt/havit/util/KeyBoardUtil.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/navigation/nav_main.xml
Labels: FEAT, UI, NAYOUNG💜

#57 [FEAT] #52 Set HomeFragment clickEvent
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeAddCategoryActivity.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryAllActivity.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryEmptyFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeSearchViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/alarm/HomeAlarmFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/contents/HomeContentsFragment.kt
  app/src/main/res/layout/activity_home_add_category.xml
  app/src/main/res/layout/activity_home_category_all.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_alarm.xml
  app/src/main/res/layout/fragment_home_contents.xml
  app/src/main/res/layout/fragment_home_search.xml
  app/src/main/res/layout/item_home_recent_contents_list.xml
  app/src/main/res/navigation/nav_main.xml
Labels: FEAT, YUBIN💙

#63 Feature/webview
  app/src/main/java/org/sopt/havit/ui/contents/WebViewModel.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/java/org/sopt/havit/util/web/CustomWebView.kt
  app/src/main/java/org/sopt/havit/util/web/DigBroadcastReceiver.kt
  app/src/main/res/drawable-hdpi/ic_contents_webread_2.png
  app/src/main/res/drawable-hdpi/ic_contents_webunread.png
  app/src/main/res/drawable-mdpi/ic_contents_webread_2.png
  app/src/main/res/drawable-mdpi/ic_contents_webunread.png
  app/src/main/res/drawable-xhdpi/ic_contents_webread_2.png
  app/src/main/res/drawable-xhdpi/ic_contents_webunread.png
  app/src/main/res/drawable-xxhdpi/ic_contents_webread_2.png
  app/src/main/res/drawable-xxhdpi/ic_contents_webunread.png
  app/src/main/res/drawable-xxxhdpi/ic_contents_webread_2.png
  app/src/main/res/drawable-xxxhdpi/ic_contents_webunread.png
  app/src/main/res/layout/view_custom_web.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, NAYOUNG💜

#65 Feature/webview
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/web/HavitBroadcastReceiver.kt
  app/src/main/java/org/sopt/havit/ui/web/SeesionHelper.kt
  app/src/main/java/org/sopt/havit/ui/web/WebFragment.kt
  app/src/main/java/org/sopt/havit/util/web/ActionBroadcastReceiver.kt
  app/src/main/java/org/sopt/havit/util/web/CustomWebView.kt
  app/src/main/java/org/sopt/havit/util/web/DigBroadcastReceiver.kt
  app/src/main/res/layout/fragment_web.xml
  app/src/main/res/navigation/nav_main.xml
Labels: FEAT, NAYOUNG💜

#68 Feature/share
  app/src/main/java/org/sopt/havit/data/CategorySelectableData.kt
  app/src/main/java/org/sopt/havit/ui/share/CategorySelectableAdapter.kt
  app/src/main/java/org/sopt/havit/ui/share/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SelectCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SetNotificationFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/color/selector_category_check.xml
  app/src/main/res/drawable-hdpi/img_category_plus.png
  app/src/main/res/drawable-mdpi/img_category_plus.png
  app/src/main/res/drawable-xhdpi/img_category_plus.png
  app/src/main/res/drawable-xxhdpi/img_category_plus.png
  app/src/main/res/drawable-xxxhdpi/img_category_plus.png
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/rectangle_black_radius_20.xml
  app/src/main/res/layout/fragment_bottom_sheet_share.xml
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/fragment_select_category.xml
  app/src/main/res/layout/fragment_set_notification.xml
  app/src/main/res/layout/item_category_selectable.xml
  app/src/main/res/layout/toast_category_added.xml
  app/src/main/res/layout/toast_contents_added.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, UI, HYORIM😎

#76 [FEAT/UI] Create Custom Delete Dialog in Category Modify View #75
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyFragment.kt
  app/src/main/res/drawable/rectangle_gray_0_radius_8.xml
  app/src/main/res/drawable/rectangle_havit_red_radius_8.xml
  app/src/main/res/drawable/rectangle_white_radius_8.xml
  app/src/main/res/layout/dilaog_category_delete.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: FEAT, UI, HYEIN💛

#83 [FEAT] SearchFragment Server Link (#81)
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/data/RetrofitObject.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsHavitRequest.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsHavitResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/SearchContentsResponse.kt
  app/src/main/java/org/sopt/havit/data/repository/SearchRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/res/drawable-hdpi/ic_search.png
  app/src/main/res/drawable-hdpi/ic_search_black.png
  app/src/main/res/drawable-hdpi/ic_search_is.png
  app/src/main/res/drawable-hdpi/img_search.png
  app/src/main/res/drawable-mdpi/ic_search.png
  app/src/main/res/drawable-mdpi/ic_search_black.png
  app/src/main/res/drawable-mdpi/ic_search_is.png
  app/src/main/res/drawable-mdpi/img_search.png
  app/src/main/res/drawable-xhdpi/ic_search.png
  app/src/main/res/drawable-xhdpi/ic_search_black.png
  app/src/main/res/drawable-xhdpi/ic_search_is.png
  app/src/main/res/drawable-xhdpi/img_search.png
  app/src/main/res/drawable-xxhdpi/ic_search.png
  app/src/main/res/drawable-xxhdpi/ic_search_black.png
  app/src/main/res/drawable-xxhdpi/ic_search_is.png
  app/src/main/res/drawable-xxhdpi/img_search.png
  app/src/main/res/drawable-xxxhdpi/ic_search.png
  app/src/main/res/drawable-xxxhdpi/ic_search_black.png
  app/src/main/res/drawable-xxxhdpi/ic_search_is.png
  app/src/main/res/drawable-xxxhdpi/img_search.png
  app/src/main/res/drawable/rectangle_white_radius_16.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: FEAT, NAYOUNG💜

#85 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/BottomSheetShareFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/IconAdapter.kt
  app/src/main/java/org/sopt/havit/ui/share/NoCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SelectCategoryFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/drawable/oval_gray.xml
  app/src/main/res/drawable/oval_gray_stroke_2.xml
  app/src/main/res/drawable/rectangle_gray_2.xml
  app/src/main/res/layout/fragment_add_category.xml
  app/src/main/res/layout/fragment_bottom_sheet_share.xml
  app/src/main/res/layout/fragment_choose_icon.xml
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/fragment_no_category.xml
  app/src/main/res/layout/item_category_icon.xml
  app/src/main/res/navigation/nav_share.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, REFACTOR, UI, HYORIM😎

#87 Feature/share
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher_havit-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_havit.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_havit_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_havit.png
  app/src/main/res/mipmap-hdpi/ic_launcher_havit_background.png
  app/src/main/res/mipmap-hdpi/ic_launcher_havit_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_havit_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_havit.png
  app/src/main/res/mipmap-mdpi/ic_launcher_havit_background.png
  app/src/main/res/mipmap-mdpi/ic_launcher_havit_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_havit_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_havit.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_havit_background.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_havit_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_havit_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_havit.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_havit_background.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_havit_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_havit_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_havit.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_havit_background.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_havit_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_havit_round.png
  app/src/main/res/values/strings.xml
Labels: UI, HYORIM😎

#100 [REFACTOR] Modify dialog_category_delete.xml name (#99)
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyFragment.kt
  app/src/main/res/layout/dialog_category_delete.xml
Labels: REFACTOR, HYEIN💛

#104 [FIX] #101 Create item_contents_simple
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/item_contents_simple.xml
Labels: FIX, YUBIN💙

#106 [FEAT] #90 Set Contents list with server in HomeFragment, ContentsSimpleActivity
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsSimpleResponse.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/res/layout/item_contents_simple.xml
  app/src/main/res/layout/item_home_recent_contents_list.xml
Labels: FEAT, YUBIN💙

#108 [FEAT] #107 Create BackBtn in HomeChildView
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/data/ContentsData.kt
  app/src/main/java/org/sopt/havit/data/HomeContentsData.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsResponse.kt
  app/src/main/java/org/sopt/havit/data/repository/SearchRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/res/color/selector_dialog_contents_top.xml
  app/src/main/res/layout/activity_contents.xml
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/dialog_contents_top.xml
  app/src/main/res/layout/fragment_contents.xml
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/layout/item_contents_linear_min.xml
  app/src/main/res/layout/item_dialog_contents_top.xml
  app/src/main/res/navigation/nav_main.xml
Labels: FEAT, YUBIN💙

#110 Feature/notification
  app/build.gradle
  app/google-services.json
  app/src/main/java/org/sopt/havit/notification/MyFirebaseMessagingService.kt
  app/src/main/res/layout/push_notification.xml
  build.gradle
Labels: FEAT, HYORIM😎

#118 Feature/webview
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/data/repository/ContentsRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/ContentsRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/contents/WebViewModel.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveActivity.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebFragment.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/anim/slide_back_to_top.xml
  app/src/main/res/anim/slide_out_from_top.xml
  app/src/main/res/drawable-hdpi/ic_refresh.png
  app/src/main/res/drawable-hdpi/ic_share.png
  app/src/main/res/drawable-mdpi/ic_refresh.png
  app/src/main/res/drawable-mdpi/ic_share.png
  app/src/main/res/drawable-xhdpi/ic_refresh.png
  app/src/main/res/drawable-xhdpi/ic_share.png
  app/src/main/res/drawable-xhdpi/rectangle_gray_0_radius_4.xml
  app/src/main/res/drawable-xxhdpi/ic_refresh.png
  app/src/main/res/drawable-xxhdpi/ic_share.png
  app/src/main/res/drawable-xxxhdpi/ic_refresh.png
  app/src/main/res/drawable-xxxhdpi/ic_share.png
  app/src/main/res/layout/activity_save.xml
  app/src/main/res/layout/activity_web.xml
  app/src/main/res/layout/fragment_save.xml
  app/src/main/res/layout/fragment_web.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  settings.gradle
Labels: FIX, NAYOUNG💜

#121 Feature/search
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsSearchResponse.kt
  app/src/main/java/org/sopt/havit/data/repository/SearchRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_web.xml
  app/src/main/res/layout/item_contents_search.xml
Labels: FEAT, NAYOUNG💜

#122 [FEAT/UI] ContentsActivity to WebActivity (#42)
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
  app/src/main/res/layout/activity_web.xml
Labels: FEAT, UI, NAYOUNG💜

#125 [FEAT] SearchActivity Adapter Feat (#102)
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/res/layout/item_contents_search.xml
Labels: FEAT, NAYOUNG💜

#127 Feat/contents
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
Labels: FEAT, UI, HYEIN💛

#130 [FIX] Change CategoryResponse url to imageUrl (#129)
  app/src/main/java/org/sopt/havit/data/remote/CategoryResponse.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryRvAdapter.kt
  app/src/main/res/layout/item_home_category_list.xml
Labels: FIX, YUBIN💙

#135 Feat/contents
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
Labels: FEAT, UI, HYEIN💛

#139 [FEAT] SaveFragment to ShareActivity (#34)
  app/src/main/java/org/sopt/havit/ui/save/SaveActivity.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_save.xml
Labels: FEAT, NAYOUNG💜

#141 [FEAT] #105 Match time format of ContentsView in HomeFragment, ContentsSimpleActivity
  app/src/main/java/org/sopt/havit/data/remote/ContentsSimpleResponse.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
  app/src/main/res/drawable-hdpi/ic_noalarm.png
  app/src/main/res/drawable-mdpi/ic_noalarm.png
  app/src/main/res/drawable-xhdpi/ic_noalarm.png
  app/src/main/res/drawable-xxhdpi/ic_noalarm.png
  app/src/main/res/drawable-xxxhdpi/ic_noalarm.png
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/item_contents_simple.xml
  app/src/main/res/layout/item_home_category_list.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, YUBIN💙

#142 [FEAT/UI/FIX] Set Default Image & Fix Havit Button in Contents (#137)
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/layout/item_contents_linear_min.xml
Labels: FIX, FEAT, UI, HYEIN💛

#144 Feature/more
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_contents_more.xml
  app/src/main/res/layout/item_contents_search.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: FEAT, UI, NAYOUNG💜

#155 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsCategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsCategoryFragment.kt
  app/src/main/res/layout/dialog_contents_top.xml
  app/src/main/res/layout/fragment_dialog_contents_category.xml
  app/src/main/res/layout/item_dialog_contents_top.xml
Labels: FIX, FEAT, UI, HYEIN💛

#160 [FEAT] #148 Set recommendContentsList with server in HomeFragment
  app/src/main/java/org/sopt/havit/data/HomeCategoryListData.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/RecommendationResponse.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryVpAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecommendRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/item_home_recommend_list.xml
Labels: FEAT, YUBIN💙

#162 [UI] SplashActivity Layout Apply (#161)
  app/src/main/java/org/sopt/havit/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-hdpi/bg_splash.png
  app/src/main/res/drawable-hdpi/ic_symbol_logo.png
  app/src/main/res/drawable-hdpi/text_logo_small.png
  app/src/main/res/drawable-mdpi/bg_splash.png
  app/src/main/res/drawable-mdpi/ic_symbol_logo.png
  app/src/main/res/drawable-mdpi/text_logo_small.png
  app/src/main/res/drawable-xhdpi/bg_splash.png
  app/src/main/res/drawable-xhdpi/ic_symbol_logo.png
  app/src/main/res/drawable-xhdpi/text_logo_small.png
  app/src/main/res/drawable-xxhdpi/bg_splash.png
  app/src/main/res/drawable-xxhdpi/ic_symbol_logo.png
  app/src/main/res/drawable-xxhdpi/text_logo_small.png
  app/src/main/res/drawable-xxxhdpi/bg_splash.png
  app/src/main/res/drawable-xxxhdpi/ic_symbol_logo.png
  app/src/main/res/drawable-xxxhdpi/text_logo_small.png
  app/src/main/res/drawable/bg_gradient_splash.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/colors.xml
Labels: UI, NAYOUNG💜

#170 Feature/webview
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/SearchContentsResponse.kt
  app/src/main/java/org/sopt/havit/data/repository/SearchRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/ContentsRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
  app/src/main/res/layout/activity_web.xml
Labels: FEAT, NAYOUNG💜

#174 [UI] ContentsItem More TouchArea Increase (#173)
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/layout/item_contents_linear_min.xml
Labels: UI, NAYOUNG💜

#177 [UI] ContentsMoreFragment title change (#176)
  app/src/main/res/layout/fragment_contents_more.xml
  app/src/main/res/layout/item_contents_search.xml
Labels: UI, NAYOUNG💜

#179 Feat/category
  app/src/main/java/org/sopt/havit/data/remote/CategoryResponse.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyAdapter.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/res/layout/activity_category_content_modify.xml
  app/src/main/res/values/themes.xml
Labels: FEAT, UI, HYEIN💛

#186 [FEAT] Start with SelectCategoryFragment (#185)
  app/src/main/java/org/sopt/havit/ui/share/NoCategoryFragment.kt
Labels: FEAT, HYORIM😎

#193 [FEAT] #190 Set ContentsAll API in ContentsActivity
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
Labels: FEAT, YUBIN💙

#196 [FEAT] ContentsSimpleAdapter More Apply (#194)
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/res/layout/item_contents_simple.xml
Labels: FEAT, NAYOUNG💜

#199 Feat/category
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryModifyRequest.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryModifyResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryOrderRequest.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryOrderResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryResponse.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryIconAdapter.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/res/layout/activity_category_order_modify.xml
Labels: FEAT, HYEIN💛

#200 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/CategorySelectableAdapter.kt
  app/src/main/java/org/sopt/havit/ui/share/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SelectCategoryFragment.kt
  app/src/main/res/drawable/rectangle_purple_2_radius_6.xml
  app/src/main/res/layout/fragment_edit_title.xml
  app/src/main/res/layout/fragment_select_category.xml
  app/src/main/res/navigation/nav_share.xml
Labels: FEAT, HYORIM😎

#195 [UI] fragment_my_page.xml ConstraintLayout Height Change (#192)
  app/src/main/res/layout/fragment_my_page.xml
Labels: UI, NAYOUNG💜

#204 [FIX] Fix Havit Button Binding error with change list's data(#203)
  app/src/main/java/org/sopt/havit/data/remote/ContentsResponse.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
Labels: FIX, HYEIN💛

#205 Feature/search
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/res/layout/item_contents_search.xml
Labels: FEAT, NAYOUNG💜

#206 [FEAT/UI] SaveFragment Process (#34)
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/res/layout/fragment_save.xml
Labels: FEAT, UI, NAYOUNG💜

#211 Feat/contents
  app/src/main/java/org/sopt/havit/data/remote/ContentsResponse.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
Labels: FIX, FEAT, HYEIN💛

#214 [UI] fragment_contents_more.xml dot change (#213)
  app/src/main/res/layout/fragment_contents_more.xml
Labels: UI, NAYOUNG💜

#218 Feature/search
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
Labels: FEAT, NAYOUNG💜

#224 [FEAT] WebviewActivity share title change
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
Labels: FEAT, NAYOUNG💜

#225 Feature/webview
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
Labels: FEAT, NAYOUNG💜

#226 [CHORE]
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/domain/Contents.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveActivity.kt
  app/src/main/res/layout/activity_save.xml
Labels: CHORE, NAYOUNG💜

#228 [FIX] Fix problem Cannot Changing Title on Contents Share Progress (#…
  app/src/main/java/org/sopt/havit/data/ContentsTitleImageData.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/res/layout/fragment_contents_summery.xml
Labels: FIX, NAYOUNG💜, HYORIM😎

#231 Feat/category
  app/src/main/java/org/sopt/havit/ui/category/CategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/share/SetNotificationFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/color/selector_alarm_check.xml
  app/src/main/res/drawable/selector_alarm_back.xml
  app/src/main/res/layout/fragment_set_notification.xml
Labels: FEAT, UI, HYEIN💛

#232 [FEAT] Set Decoration for each item of Search(#230)
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_contents_search.xml
Labels: FEAT, UI, HYEIN💛

#233 Feature/share
  app/src/main/java/org/sopt/havit/ShareActivity.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/CreateContentsRequest.kt
  app/src/main/java/org/sopt/havit/data/remote/CreateContentsResponse.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/EditTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SetNotificationFragment.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/layout/fragment_set_notification.xml
  app/src/main/res/layout/item_contents_linear_min.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, UI, HYORIM😎

#234 [FEAT/FIX] WebActivity Share Url & Search isHavit Fix
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/res/layout/item_contents_search.xml
Labels: FIX, FEAT, NAYOUNG💜

#237 Feature/share
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SetNotificationFragment.kt
Labels: FEAT, HYORIM😎

#245 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/EditTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SelectCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SetNotificationFragment.kt
  app/src/main/java/org/sopt/havit/util/CallbackUtil.kt
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/push_notification.xml
  app/src/main/res/navigation/nav_share.xml
Labels: FEAT, UI, HYORIM😎
