Repository TeamHavit/Havit-Android, pull requests merged in 2022-05, with the labels that each got.

#520 Hilt
  app/build.gradle
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/data/mapper/ContentsMapper.kt
  app/src/main/java/org/sopt/havit/data/repository/ContentsRepository.kt
  app/src/main/java/org/sopt/havit/data/repository/ContentsRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/repository/MyPageRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/repository/SearchRepository.kt
  app/src/main/java/org/sopt/havit/data/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/source/SearchRemoteDataSource.kt
  app/src/main/java/org/sopt/havit/data/source/SearchRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/havit/di/DataSourceModule.kt
  app/src/main/java/org/sopt/havit/di/RepositoryModule.kt
  app/src/main/java/org/sopt/havit/di/RetrofitModule.kt
  app/src/main/java/org/sopt/havit/di/ServiceModule.kt
  app/src/main/java/org/sopt/havit/di/SharedPreferencesModule.kt
  app/src/main/java/org/sopt/havit/di/UseCaseModule.kt
  app/src/main/java/org/sopt/havit/domain/entity/Contents.kt
  app/src/main/java/org/sopt/havit/domain/repository/ContentsRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/MyPageRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/SearchRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/domain/usecase/SearchUseCase.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_contents_search.xml
  build.gradle
Labels: REFACTOR, NAYOUNG💜

#534 Feature/setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/data/remote/UserResponse.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingAlarmActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingNoticeActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingPersonalDataActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingPolicyActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingUnregisterActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingViewModel.kt
  app/src/main/res/drawable-hdpi/ic_check_active.png
  app/src/main/res/drawable-hdpi/ic_check_inactive.png
  app/src/main/res/drawable-hdpi/ic_delete_text_gray.png
  app/src/main/res/drawable-mdpi/ic_check_active.png
  app/src/main/res/drawable-mdpi/ic_check_inactive.png
  app/src/main/res/drawable-mdpi/ic_delete_text_gray.png
  app/src/main/res/drawable-xhdpi/ic_check_active.png
  app/src/main/res/drawable-xhdpi/ic_check_inactive.png
  app/src/main/res/drawable-xhdpi/ic_delete_text_gray.png
  app/src/main/res/drawable-xxhdpi/ic_check_active.png
  app/src/main/res/drawable-xxhdpi/ic_check_inactive.png
  app/src/main/res/drawable-xxhdpi/ic_delete_text_gray.png
  app/src/main/res/drawable-xxxhdpi/ic_check_active.png
  app/src/main/res/drawable-xxxhdpi/ic_check_inactive.png
  app/src/main/res/drawable-xxxhdpi/ic_delete_text_gray.png
  app/src/main/res/drawable/img_privacy_policy.png
  app/src/main/res/drawable/img_tos.png
  app/src/main/res/drawable/selector_switch_track.xml
  app/src/main/res/drawable/switch_track_off.xml
  app/src/main/res/drawable/switch_track_on.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_setting_alarm.xml
  app/src/main/res/layout/activity_setting_modify.xml
  app/src/main/res/layout/activity_setting_notice.xml
  app/src/main/res/layout/activity_setting_personal_data.xml
  app/src/main/res/layout/activity_setting_policy.xml
  app/src/main/res/layout/activity_setting_unregister.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎, YUBIN💙

#531 [REFACTOR] SavaFragment ClipData 및 EditTextListener 로직 개선 (#530)
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveViewModel.kt
  app/src/main/res/layout/fragment_save.xml
Labels: REFACTOR, NAYOUNG💜

#536 [FEAT] 알림 환경설정 값에 따른 notification 생성 여부 결정 (#535)
  app/build.gradle
  app/src/main/java/org/sopt/havit/MyFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/data/local/SettingPreference.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingAlarmActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingUnregisterActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/viewmodel/SettingAlarmViewModel.kt
  app/src/main/java/org/sopt/havit/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_setting_alarm.xml
  app/src/main/res/layout/activity_setting_modify.xml
  app/src/main/res/layout/activity_setting_unregister.xml
Labels: FEAT, HYORIM😎

#540 [FIX] WebActivity @AndroidEntryPoint 코드 추가 (#539)
  app/src/main/java/org/sopt/havit/di/RetrofitModule.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
Labels: FIX, NAYOUNG💜

#544 Feature/share
  app/src/main/java/org/sopt/havit/data/remote/CreateContentsRequest.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SelectCategoryFragment.kt
  app/src/main/res/layout/layout_share_select_category.xml
Labels: FIX, FEAT, HYORIM😎

#546 [REFACTOR] SaveFragment 키보드 올리기 코드 수정 및 개선 (#545)
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/res/layout/fragment_save.xml
Labels: REFACTOR, NAYOUNG💜

#555 [FEAT] 컨텐츠뷰 더보기 - 공유하기 기능 개발 (#553)
  app/src/main/java/org/sopt/havit/ui/contents/ContentsMoreFragment.kt
Labels: FEAT, HYORIM😎

#565 [FIX] SaveFragment EditText 커서 이동 버그 수정 완료 (#564)
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveViewModel.kt
Labels: FIX, NAYOUNG💜

#562 Feature/home
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationViewModel.kt
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/activity_contents_simple_skeleton.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_skeleton.xml
  app/src/main/res/layout/item_contents_simple_skeleton.xml
  app/src/main/res/layout/item_notification.xml
Labels: FIX, FEAT, YUBIN💙

#568 [REFACTOR] 마이페이지 일러스트 지연 현상 코드 수정
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
Labels: REFACTOR, NAYOUNG💜

#566 Feature/onboarding
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingFifthFragment.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingFirstFragment.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingFourthFragment.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingSecondFragment.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingThirdFragment.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingVpAdapter.kt
  app/src/main/res/drawable-hdpi/img_onboarding_1.png
  app/src/main/res/drawable-hdpi/img_onboarding_2.png
  app/src/main/res/drawable-hdpi/img_onboarding_3.png
  app/src/main/res/drawable-hdpi/img_onboarding_4.png
  app/src/main/res/drawable-hdpi/img_onboarding_5.png
  app/src/main/res/drawable-mdpi/img_onboarding_1.png
  app/src/main/res/drawable-mdpi/img_onboarding_2.png
  app/src/main/res/drawable-mdpi/img_onboarding_3.png
  app/src/main/res/drawable-mdpi/img_onboarding_4.png
  app/src/main/res/drawable-mdpi/img_onboarding_5.png
  app/src/main/res/drawable-xhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xhdpi/img_onboarding_2.png
  app/src/main/res/drawable-xhdpi/img_onboarding_3.png
  app/src/main/res/drawable-xhdpi/img_onboarding_4.png
  app/src/main/res/drawable-xhdpi/img_onboarding_5.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_2.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_3.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_4.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_5.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_2.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_3.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_4.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_5.png
  app/src/main/res/drawable/rectangle_gray_1_radius_11.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_fifth.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_fourth.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: FEAT, UI, HYEIN💛

#571 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsCategoryFragment.kt
  app/src/main/res/color/selector_contents_category_dialog_background.xml
  app/src/main/res/color/selector_dialog_contents_top.xml
  app/src/main/res/drawable/line_gray_0.xml
  app/src/main/res/drawable/rectangle_gray_0_radius_5.xml
  app/src/main/res/drawable/rectangle_white_gray_radius_24.xml
  app/src/main/res/drawable/rectangle_white_radius_24.xml
  app/src/main/res/layout/fragment_dialog_contents_category.xml
  app/src/main/res/layout/fragment_empty_contents.xml
  app/src/main/res/layout/fragment_save.xml
  app/src/main/res/layout/item_dialog_contents_top.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: FEAT, UI, HYEIN💛

#572 Feat/category
  app/build.gradle
  app/src/main/java/org/sopt/havit/data/remote/CategoryResponse.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/res/layout/activity_category_order_modify.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/item_category_skeleton.xml
  app/src/main/res/values/strings.xml
Labels: FIX, FEAT, REFACTOR, HYEIN💛

#577 [REFACTOR] 다른 카카오 계정으로 로그인 기능 코드 수정 (#576)
  app/src/main/java/org/sopt/havit/ui/sign/SignInViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
Labels: REFACTOR, NAYOUNG💜
