Repository TeamHavit/Havit-Android, pull requests merged in 2022-10, with the labels that each got.

#759 Feature/share
  app/src/main/java/org/sopt/havit/data/repository/ContentsRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/di/RepositoryModule.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationActivity.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationViewModel.kt
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingUnregisterActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/edit_title/EditTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/AddTosFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignUpViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
  app/src/main/java/org/sopt/havit/util/HavitSharedPreference.kt
  app/src/main/res/layout/fragment_contents_summery.xml
Labels: REFACTOR, HYORIM😎

#760 [REFACTOR] ContentsSummeryFragment / 크롤링 로직 ShareActivity로 이동 (#758)
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
Labels: REFACTOR, HYORIM😎

#762 [FIX] WebViewActivity 인앱 브라우저 / 외부 브라우저 연결 버그 수정 (#761)
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
Labels: FIX, NAYOUNG💜

#764 [FIX] ogTag에 url 데이터가 없는 경우 콘텐츠 저장에 실패하는 버그 수정 (#763)
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
Labels: FIX, HYORIM😎

#766 [CHORE] Sementic Versioning v1.0.0 적용 (#765)
  app/build.gradle
Labels: CHORE, HYORIM😎
