Repository TeamHavit/Havit-Android, pull requests merged in 2022-11, with the labels that each got.

#772 [FIX] HomeFragment Viewpager2 page가 임의로 움직이는 버그수정 (#771)
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
Labels: FIX, HYORIM😎

#774 [FEAT] push api 변경사항 반영 (#770)
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
Labels: FEAT, HYORIM😎

#775 [FIX] 컨텐츠 저장시 제목 수정이 안되는 에러 수정 (#773)
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/edit_title/EditTitleFragment.kt
Labels: FIX, HYORIM😎

#776 [FIX] 컨텐츠 저장시 Viewpager2 page가 임의로 움직이는 버그수정 (#771)
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryVpAdapter.kt
Labels: FIX, HYORIM😎

#778 [FIX] ContentsSimpleViewModel -> @HiltViewModel 적용 (#777)
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
Labels: FIX, HYORIM😎

#780 [FIX] 최근저장 콘텐츠 -> 카테고리 width adjust 버그 수정 (#779)
  app/src/main/res/layout/item_home_recent_contents_list.xml
Labels: FIX, HYORIM😎

#789 [FEAT] Dev, Prod 서버 분리로 인한 세팅 변경 (#788)
  .gitignore
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/data/RetrofitObject.kt
  app/src/main/java/org/sopt/havit/di/RetrofitModule.kt
Labels: FEAT, HYORIM😎

#791 [CHORE] local.properties 에 카카오 api 키 추가 (#790)
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/MainApplication.kt
Labels: CHORE, NAYOUNG💜

#793 [UI] 약관 및 정책 시행날짜 변경으로 인한 img 교체 (#792)
  app/src/main/res/drawable-hdpi/img_policy.png
  app/src/main/res/drawable-mdpi/img_policy.png
  app/src/main/res/drawable-xhdpi/img_policy.png
  app/src/main/res/drawable-xxhdpi/img_policy.png
  app/src/main/res/drawable-xxxhdpi/img_policy.png
Labels: UI, HYORIM😎

#795 [FIX] home/ 모든 컨텐츠의 수가 카테고리수로 표시되는 에러 수정 (#794)
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
Labels: FIX, HYORIM😎

#797 [FIX] 크롤링 되지 않는 컨텐츠 저장 (#796)
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
Labels: FIX, HYORIM😎

#799 [FIX] ContentsSummeryFragment / 엠티뷰 radius 처리 (#798)
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/values/styles.xml
Labels: FIX, HYORIM😎

#800 [BACKMERGE] release v1.0.0 코드 develop반영
  .gitignore
  app/build.gradle
  app/google-services.json
  app/release/output-metadata.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/data/RetrofitObject.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsSimpleResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/NotificationResponse.kt
  app/src/main/java/org/sopt/havit/di/RetrofitModule.kt
  app/src/main/java/org/sopt/havit/domain/entity/Contents.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryVpAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/edit_title/EditTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/java/org/sopt/havit/util/CalenderUtil.kt
  app/src/main/res/drawable-hdpi/img_policy.png
  app/src/main/res/drawable-mdpi/img_policy.png
  app/src/main/res/drawable-xhdpi/img_policy.png
  app/src/main/res/drawable-xxhdpi/img_policy.png
  app/src/main/res/drawable-xxxhdpi/img_policy.png
  app/src/main/res/layout/fragment_contents_more.xml
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/layout/item_contents_linear_min.xml
  app/src/main/res/layout/item_contents_search.xml
  app/src/main/res/layout/item_contents_simple.xml
  app/src/main/res/layout/item_home_recent_contents_list.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: HYORIM😎

#802 [FIX] MediatorLiveData addSource 중복 제거 (#801)
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
Labels: FIX, HYORIM😎

#805 [FIX] MediatorLiveData removeSource (#804)
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
Labels: FIX, HYORIM😎

#806 [CHORE] Dev 모드의 아이콘 변경 (#803)
  app/src/dev/ic_launcher_havit-playstore.png
  app/src/dev/res/mipmap-anydpi-v26/ic_launcher_havit.xml
  app/src/dev/res/mipmap-anydpi-v26/ic_launcher_havit_round.xml
  app/src/dev/res/mipmap-hdpi/ic_launcher_havit.png
  app/src/dev/res/mipmap-hdpi/ic_launcher_havit_background.png
  app/src/dev/res/mipmap-hdpi/ic_launcher_havit_foreground.png
  app/src/dev/res/mipmap-hdpi/ic_launcher_havit_round.png
  app/src/dev/res/mipmap-mdpi/ic_launcher_havit.png
  app/src/dev/res/mipmap-mdpi/ic_launcher_havit_background.png
  app/src/dev/res/mipmap-mdpi/ic_launcher_havit_foreground.png
  app/src/dev/res/mipmap-mdpi/ic_launcher_havit_round.png
  app/src/dev/res/mipmap-xhdpi/ic_launcher_havit.png
  app/src/dev/res/mipmap-xhdpi/ic_launcher_havit_background.png
  app/src/dev/res/mipmap-xhdpi/ic_launcher_havit_foreground.png
  app/src/dev/res/mipmap-xhdpi/ic_launcher_havit_round.png
  app/src/dev/res/mipmap-xxhdpi/ic_launcher_havit.png
  app/src/dev/res/mipmap-xxhdpi/ic_launcher_havit_background.png
  app/src/dev/res/mipmap-xxhdpi/ic_launcher_havit_foreground.png
  app/src/dev/res/mipmap-xxhdpi/ic_launcher_havit_round.png
  app/src/dev/res/mipmap-xxxhdpi/ic_launcher_havit.png
  app/src/dev/res/mipmap-xxxhdpi/ic_launcher_havit_background.png
  app/src/dev/res/mipmap-xxxhdpi/ic_launcher_havit_foreground.png
  app/src/dev/res/mipmap-xxxhdpi/ic_launcher_havit_round.png
Labels: UI, HYORIM😎

#808 [CHORE] prod applicationIdSuffix 제거 (#807)
  app/build.gradle
Labels: CHORE, HYORIM😎
