Repository TeamHavit/Havit-Android, pull requests merged in 2022-04, with the labels that each got.

#474 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsCategoryFragment.kt
  app/src/main/java/org/sopt/havit/util/CustomToast.kt
  app/src/main/res/anim/slide_back_to_top.xml
  app/src/main/res/anim/slide_out_from_top.xml
  app/src/main/res/drawable/rectangle_purple_main_radius_44.xml
  app/src/main/res/layout/activity_contents.xml
  app/src/main/res/layout/fragment_contents_more.xml
  app/src/main/res/layout/fragment_dialog_contents_category.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, REFACTOR, UI, HYEIN💛

#478 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/res/layout/activity_contents.xml
Labels: FIX, HYEIN💛

#475 Feature/home
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_home_category.xml
Labels: FIX, CHORE, UI, YUBIN💙

#480 [REFACTOR] feature/login 브랜치 생성 및 카카오 로그인 코드 간결화 (#468)
  app/src/main/java/org/sopt/havit/ui/sign/SignInActivity.kt
Labels: REFACTOR, NAYOUNG💜

#481 [REFACTOR] feature/my_page 브랜치 생성 및 마이페이지 화면 이동 (#469)
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
Labels: REFACTOR, NAYOUNG💜

#487 Feature/home
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryVpAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/item_home_category_list.xml
  app/src/main/res/layout/item_home_recent_contents_list.xml
  app/src/main/res/layout/layout_home_category.xml
  app/src/main/res/layout/layout_home_category_empty.xml
Labels: REFACTOR, YUBIN💙

#486 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/BottomSheetShareFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/EditTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SetNotificationFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/util/AutoClearedValue.kt
  app/src/main/java/org/sopt/havit/util/FragmentExtensions.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/java/org/sopt/havit/util/OnBackPressedHandler.kt
  app/src/main/res/layout/fragment_edit_title.xml
  app/src/main/res/layout/fragment_set_notification.xml
Labels: FEAT, HYORIM😎

#484 Feat/contents
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/res/layout/activity_contents.xml
  app/src/main/res/layout/fragment_dialog_contents_category.xml
Labels: FEAT, UI, HYEIN💛

#498 Feat/contents
  app/src/main/java/org/sopt/havit/data/remote/ContentsMoreData.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
Labels: FIX, HYEIN💛

#507 [UI] Icon 딤처리 (#506)
  app/src/main/java/org/sopt/havit/ui/share/IconAdapter.kt
  app/src/main/res/drawable/ic_oval_check_62_with_stroke_1_5.xml
  app/src/main/res/layout/item_category_icon.xml
  app/src/main/res/values/strings.xml
Labels: UI, HYORIM😎

#500 Feature/login
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/sign/AddNickNameFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/AddTosFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInViewModel.kt
  app/src/main/res/drawable-hdpi/ic_check.png
  app/src/main/res/drawable-hdpi/ic_un_check.png
  app/src/main/res/drawable-mdpi/ic_check.png
  app/src/main/res/drawable-mdpi/ic_un_check.png
  app/src/main/res/drawable-xhdpi/ic_check.png
  app/src/main/res/drawable-xhdpi/ic_un_check.png
  app/src/main/res/drawable-xxhdpi/ic_check.png
  app/src/main/res/drawable-xxhdpi/ic_un_check.png
  app/src/main/res/drawable-xxxhdpi/ic_check.png
  app/src/main/res/drawable-xxxhdpi/ic_un_check.png
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/layout/fragment_add_nick_name.xml
  app/src/main/res/layout/fragment_add_tos.xml
  app/src/main/res/layout/fragment_sign_in.xml
  app/src/main/res/navigation/nav_sign.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, UI, NAYOUNG💜

#505 Feat/contents
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsFilterFragment.kt
  app/src/main/res/drawable-hdpi/ic_layout_3.png
  app/src/main/res/drawable-mdpi/ic_layout_3.png
  app/src/main/res/drawable-xhdpi/ic_layout_3.png
  app/src/main/res/drawable-xxhdpi/ic_layout_3.png
  app/src/main/res/drawable-xxxhdpi/ic_layout_3.png
  app/src/main/res/layout/fragment_dialog_contents_filter.xml
Labels: REFACTOR, UI, HYEIN💛

#514 Feature/home
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/layout/activity_contents_simple.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_contents_simple.xml
  app/src/main/res/layout/item_home_category_recyclerview.xml
  app/src/main/res/values/strings.xml
Labels: FIX, REFACTOR, YUBIN💙

#521 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsMoreFragment.kt
  app/src/main/java/org/sopt/havit/util/DialogUtil.kt
  app/src/main/res/values/strings.xml
Labels: FIX, FEAT, HYEIN💛
