Repository TeamHavit/Havit-Android, pull requests merged in 2022-03, with the labels that each got.

#359 Feature/share
  app/src/main/java/org/sopt/havit/ui/category/CategoryIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SelectCategoryFragment.kt
  app/src/main/res/drawable/rectangle_havit_gray.xml
  app/src/main/res/drawable/rectangle_havit_purple.xml
  app/src/main/res/drawable/rectangle_toast_black_radius_20.xml
  app/src/main/res/drawable/rectangle_toast_black_radius_24.xml
  app/src/main/res/drawable/rectangle_toast_black_radius_40.xml
  app/src/main/res/layout/dialog_cancel_edit_title.xml
  app/src/main/res/layout/dialog_category_delete.xml
  app/src/main/res/layout/fragment_choose_icon.xml
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/toast_category_added.xml
  app/src/main/res/layout/toast_contents_added.xml
  app/src/main/res/layout/toast_havit_complete.xml
  app/src/main/res/layout/toast_max_category.xml
  app/src/main/res/layout/toast_text.xml
  app/src/main/res/layout/toast_url_unavailable.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: CHORE, UI, HYORIM😎

#355 Feature/home
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryEmptyFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/res/drawable-hdpi/bg_card_service_use.png
  app/src/main/res/drawable-hdpi/ic_logo_small.png
  app/src/main/res/drawable-hdpi/ic_logo_small_gray.png
  app/src/main/res/drawable-hdpi/ic_main_corner_left.png
  app/src/main/res/drawable-hdpi/ic_main_corner_right.png
  app/src/main/res/drawable-hdpi/ic_serviceguide.png
  app/src/main/res/drawable-mdpi/bg_card_service_use.png
  app/src/main/res/drawable-mdpi/ic_logo_small.png
  app/src/main/res/drawable-mdpi/ic_logo_small_gray.png
  app/src/main/res/drawable-mdpi/ic_main_corner_left.png
  app/src/main/res/drawable-mdpi/ic_main_corner_right.png
  app/src/main/res/drawable-mdpi/ic_serviceguide.png
  app/src/main/res/drawable-xhdpi/bg_card_service_use.png
  app/src/main/res/drawable-xhdpi/ic_logo_small.png
  app/src/main/res/drawable-xhdpi/ic_logo_small_gray.png
  app/src/main/res/drawable-xhdpi/ic_main_corner_left.png
  app/src/main/res/drawable-xhdpi/ic_main_corner_right.png
  app/src/main/res/drawable-xhdpi/ic_serviceguide.png
  app/src/main/res/drawable-xxhdpi/bg_card_service_use.png
  app/src/main/res/drawable-xxhdpi/ic_logo_small.png
  app/src/main/res/drawable-xxhdpi/ic_logo_small_gray.png
  app/src/main/res/drawable-xxhdpi/ic_main_corner_left.png
  app/src/main/res/drawable-xxhdpi/ic_main_corner_right.png
  app/src/main/res/drawable-xxhdpi/ic_serviceguide.png
  app/src/main/res/drawable-xxxhdpi/bg_card_service_use.png
  app/src/main/res/drawable-xxxhdpi/ic_logo_small.png
  app/src/main/res/drawable-xxxhdpi/ic_logo_small_gray.png
  app/src/main/res/drawable-xxxhdpi/ic_main_corner_left.png
  app/src/main/res/drawable-xxxhdpi/ic_main_corner_right.png
  app/src/main/res/drawable-xxxhdpi/ic_serviceguide.png
  app/src/main/res/drawable/bg_white_gradient_radius_16.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_category_empty.xml
  app/src/main/res/layout/item_home_category_list.xml
  app/src/main/res/layout/item_home_recent_contents_list.xml
  app/src/main/res/layout/layout_home_category.xml
Labels: FIX, UI, YUBIN💙

#363 Feature/save
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/res/drawable-hdpi/ic_delete_text.png
  app/src/main/res/drawable-hdpi/ic_delete_toast.png
  app/src/main/res/drawable-hdpi/ic_notice.png
  app/src/main/res/drawable-mdpi/ic_delete_text.png
  app/src/main/res/drawable-mdpi/ic_delete_toast.png
  app/src/main/res/drawable-mdpi/ic_notice.png
  app/src/main/res/drawable-xhdpi/ic_delete_text.png
  app/src/main/res/drawable-xhdpi/ic_delete_toast.png
  app/src/main/res/drawable-xhdpi/ic_notice.png
  app/src/main/res/drawable-xxhdpi/ic_delete_text.png
  app/src/main/res/drawable-xxhdpi/ic_delete_toast.png
  app/src/main/res/drawable-xxhdpi/ic_notice.png
  app/src/main/res/drawable-xxxhdpi/ic_delete_text.png
  app/src/main/res/drawable-xxxhdpi/ic_delete_toast.png
  app/src/main/res/drawable-xxxhdpi/ic_notice.png
  app/src/main/res/drawable/bg_save_paste_toast.xml
  app/src/main/res/layout/fragment_save.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: FEAT, UI, NAYOUNG💜

#370 [FIX] 콘텐츠 더보기->삭제 버튼 클릭이벤트 구현 (#369)
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
Labels: FIX, YUBIN💙

#379 Feature/share
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: FEAT, HYORIM😎

#365 [REFACTOR] Savefragment 오타 수정 & 코드개선 (#364)
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/res/layout/fragment_save.xml
Labels: REFACTOR, NAYOUNG💜

#388 Feat/category
  app/src/main/res/drawable-hdpi/ic_notice_gray.png
  app/src/main/res/drawable-hdpi/ic_notice_red.png
  app/src/main/res/drawable-hdpi/ic_red_notice.png
  app/src/main/res/drawable-mdpi/ic_notice_gray.png
  app/src/main/res/drawable-mdpi/ic_notice_red.png
  app/src/main/res/drawable-mdpi/ic_red_notice.png
  app/src/main/res/drawable-xhdpi/ic_notice_gray.png
  app/src/main/res/drawable-xhdpi/ic_notice_red.png
  app/src/main/res/drawable-xhdpi/ic_red_notice.png
  app/src/main/res/drawable-xxhdpi/ic_notice_gray.png
  app/src/main/res/drawable-xxhdpi/ic_notice_red.png
  app/src/main/res/drawable-xxhdpi/ic_red_notice.png
  app/src/main/res/drawable-xxxhdpi/ic_notice_gray.png
  app/src/main/res/drawable-xxxhdpi/ic_notice_red.png
  app/src/main/res/drawable-xxxhdpi/ic_red_notice.png
  app/src/main/res/layout/activity_category_order_modify.xml
  app/src/main/res/layout/fragment_add_category.xml
  app/src/main/res/layout/fragment_save.xml
Labels: FIX, UI, HYEIN💛

#381 Feature/search
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/java/org/sopt/havit/util/DpToPxUtil.kt
  app/src/main/res/drawable-hdpi/ic_search.png
  app/src/main/res/drawable-hdpi/ic_search_is.png
  app/src/main/res/drawable-hdpi/ic_search_no.png
  app/src/main/res/drawable-hdpi/img_search.png
  app/src/main/res/drawable-mdpi/ic_search.png
  app/src/main/res/drawable-mdpi/ic_search_is.png
  app/src/main/res/drawable-mdpi/ic_search_no.png
  app/src/main/res/drawable-mdpi/img_search.png
  app/src/main/res/drawable-xhdpi/ic_search.png
  app/src/main/res/drawable-xhdpi/ic_search_is.png
  app/src/main/res/drawable-xhdpi/ic_search_no.png
  app/src/main/res/drawable-xhdpi/img_search.png
  app/src/main/res/drawable-xxhdpi/ic_search.png
  app/src/main/res/drawable-xxhdpi/ic_search_is.png
  app/src/main/res/drawable-xxhdpi/ic_search_no.png
  app/src/main/res/drawable-xxhdpi/img_search.png
  app/src/main/res/drawable-xxxhdpi/ic_search.png
  app/src/main/res/drawable-xxxhdpi/ic_search_is.png
  app/src/main/res/drawable-xxxhdpi/ic_search_no.png
  app/src/main/res/drawable-xxxhdpi/img_search.png
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_contents_search.xml
  app/src/main/res/values/dimens.xml
Labels: FEAT, REFACTOR, NAYOUNG💜

#352 Feature/mypage
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/ui/mypage/ContentsFromMyPageActivity.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/drawable-hdpi/ic_illust_stage_1.png
  app/src/main/res/drawable-hdpi/ic_illust_stage_2.png
  app/src/main/res/drawable-hdpi/ic_illust_stage_3.png
  app/src/main/res/drawable-hdpi/ic_illust_stage_4.png
  app/src/main/res/drawable-hdpi/ic_setting.png
  app/src/main/res/drawable-mdpi/ic_illust_stage_1.png
  app/src/main/res/drawable-mdpi/ic_illust_stage_2.png
  app/src/main/res/drawable-mdpi/ic_illust_stage_3.png
  app/src/main/res/drawable-mdpi/ic_illust_stage_4.png
  app/src/main/res/drawable-mdpi/ic_setting.png
  app/src/main/res/drawable-xhdpi/ic_illust_stage_1.png
  app/src/main/res/drawable-xhdpi/ic_illust_stage_2.png
  app/src/main/res/drawable-xhdpi/ic_illust_stage_3.png
  app/src/main/res/drawable-xhdpi/ic_illust_stage_4.png
  app/src/main/res/drawable-xhdpi/ic_setting.png
  app/src/main/res/drawable-xxhdpi/ic_illust_stage_1.png
  app/src/main/res/drawable-xxhdpi/ic_illust_stage_2.png
  app/src/main/res/drawable-xxhdpi/ic_illust_stage_3.png
  app/src/main/res/drawable-xxhdpi/ic_illust_stage_4.png
  app/src/main/res/drawable-xxhdpi/ic_setting.png
  app/src/main/res/drawable-xxxhdpi/ic_illust_stage_1.png
  app/src/main/res/drawable-xxxhdpi/ic_illust_stage_2.png
  app/src/main/res/drawable-xxxhdpi/ic_illust_stage_3.png
  app/src/main/res/drawable-xxxhdpi/ic_illust_stage_4.png
  app/src/main/res/drawable-xxxhdpi/ic_setting.png
  app/src/main/res/layout/activity_contents_from_my_page.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/strings.xml
Labels: UI, NAYOUNG💜

#387 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsFilterFragment.kt
  app/src/main/res/color/selector_contents_order.xml
  app/src/main/res/color/selector_contents_order_text.xml
  app/src/main/res/drawable-hdpi/img_graphic_nocategory.png
  app/src/main/res/drawable-hdpi/img_graphic_nocontents.png
  app/src/main/res/drawable-mdpi/img_graphic_nocategory.png
  app/src/main/res/drawable-mdpi/img_graphic_nocontents.png
  app/src/main/res/drawable-xhdpi/img_graphic_nocategory.png
  app/src/main/res/drawable-xhdpi/img_graphic_nocontents.png
  app/src/main/res/drawable-xxhdpi/img_graphic_nocategory.png
  app/src/main/res/drawable-xxhdpi/img_graphic_nocontents.png
  app/src/main/res/drawable-xxxhdpi/img_graphic_nocategory.png
  app/src/main/res/drawable-xxxhdpi/img_graphic_nocontents.png
  app/src/main/res/layout/activity_contents.xml
  app/src/main/res/layout/dialog_contents_order.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_dialog_contents_filter.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, REFACTOR, UI, HYEIN💛

#394 Feat/contents
  app/build.gradle
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/res/layout/activity_contents.xml
  app/src/main/res/layout/item_contents_skeleton_linear_min.xml
Labels: FIX, FEAT, UI, HYEIN💛

#399 Feature/share
  .gitignore
  app/src/main/java/org/sopt/havit/ContentsFinalData.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryAddActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryNameFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/DialogCategoryAddFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/IconAdapter.kt
  app/src/main/java/org/sopt/havit/util/CustomToast.kt
  app/src/main/res/layout/fragment_add_category.xml
  app/src/main/res/layout/fragment_category_icon.xml
  app/src/main/res/layout/fragment_category_name.xml
  app/src/main/res/layout/fragment_choose_icon.xml
  app/src/main/res/layout/toast_category_added.xml
  app/src/main/res/navigation/nav_category_add.xml
  app/src/main/res/navigation/nav_share.xml
  app/src/main/res/values/strings.xml
Labels: REFACTOR, HYORIM😎

#391 Feature/search
  app/src/main/java/org/sopt/havit/data/remote/ContentsSearchResponse.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
Labels: REFACTOR, NAYOUNG💜

#396 Feature/home
  app/src/main/java/org/sopt/havit/data/remote/NotificationResponse.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationViewModel.kt
  app/src/main/java/org/sopt/havit/util/PopupSharedPreference.kt
  app/src/main/res/drawable-hdpi/ic_alarm_active.png
  app/src/main/res/drawable-hdpi/ic_alarmtag_gray_inactive.png
  app/src/main/res/drawable-mdpi/ic_alarm_active.png
  app/src/main/res/drawable-mdpi/ic_alarmtag_gray_inactive.png
  app/src/main/res/drawable-xhdpi/ic_alarm_active.png
  app/src/main/res/drawable-xhdpi/ic_alarmtag_gray_inactive.png
  app/src/main/res/drawable-xxhdpi/ic_alarm_active.png
  app/src/main/res/drawable-xxhdpi/ic_alarmtag_gray_inactive.png
  app/src/main/res/drawable-xxxhdpi/ic_alarm_active.png
  app/src/main/res/drawable-xxxhdpi/ic_alarmtag_gray_inactive.png
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, YUBIN💙

#408 [FIX] ClipBoard Null 에러처리 (#407)
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
Labels: FIX, NAYOUNG💜

#406 [FEAT] 크롤링 방식 jsoup으로 변경
  app/build.gradle
  app/src/main/java/org/sopt/havit/data/ContentsSummeryData.kt
  app/src/main/java/org/sopt/havit/data/ContentsTitleImageData.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsScrapResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/ContentsSummeryData.kt
  app/src/main/java/org/sopt/havit/ui/share/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/drawable-hdpi/img_no_category.png
  app/src/main/res/drawable-hdpi/img_nocategory.png
  app/src/main/res/drawable-mdpi/img_no_category.png
  app/src/main/res/drawable-mdpi/img_nocategory.png
  app/src/main/res/drawable-xhdpi/img_no_category.png
  app/src/main/res/drawable-xhdpi/img_nocategory.png
  app/src/main/res/drawable-xxhdpi/img_no_category.png
  app/src/main/res/drawable-xxhdpi/img_nocategory.png
  app/src/main/res/drawable-xxxhdpi/img_no_category.png
  app/src/main/res/drawable-xxxhdpi/img_nocategory.png
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/fragment_no_category.xml
Labels: FIX, FEAT, UI, HYORIM😎

#420 Feat/category
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyViewModel.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryIconAdapter.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsFilterFragment.kt
  app/src/main/res/color/selector_category_modify_text.xml
  app/src/main/res/layout/activity_category_content_modify.xml
  app/src/main/res/layout/fragment_dialog_contents_filter.xml
Labels: FEAT, REFACTOR, UI, HYEIN💛

#438 Feat/category
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/res/drawable-hdpi/img_add_category_tip.png
  app/src/main/res/drawable-mdpi/img_add_category_tip.png
  app/src/main/res/drawable-xhdpi/img_add_category_tip.png
  app/src/main/res/drawable-xxhdpi/img_add_category_tip.png
  app/src/main/res/drawable-xxxhdpi/img_add_category_tip.png
  app/src/main/res/layout/activity_category_content_modify.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/toast_text.xml
  app/src/main/res/values/strings.xml
Labels: FIX, FEAT, UI, HYEIN💛

#433 Feature/save
  app/src/main/res/layout/fragment_save.xml
  app/src/main/res/values/strings.xml
Labels: REFACTOR, UI, NAYOUNG💜

#462 Feature/share
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/BottomSheetShareFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/PickerFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SetNotificationFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/res/layout/fragment_picker.xml
  app/src/main/res/values/strings.xml
Labels: FIX, FEAT, HYORIM😎

#464 Feature/sign
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/kakao/SignInViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInViewModel.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/layout/activity_sign_in.xml
Labels: FIX, HYORIM😎

#465 Feature/mypage
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/kakao/SignInViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInViewModel.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: FIX

#467 Feature/share
  .gitignore
  app/src/main/java/org/sopt/havit/ui/share/PickerFragment.kt
  app/src/main/java/org/sopt/havit/util/DialogUtil.kt
  app/src/main/res/anim/slide_right_to_left_hide.xml
  app/src/main/res/anim/slide_right_to_left_show.xml
  app/src/main/res/layout/activity_contents.xml
  app/src/main/res/layout/dialog_havit_util.xml
  app/src/main/res/layout/fragment_contents_more.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_contents_linear_min.xml
  app/src/main/res/navigation/nav_share.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: UI, HYORIM😎
