Repository TeamHavit/Havit-Android, pull requests merged in 2022-02, with the labels that each got.

#250 Feature/share
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ContentsSummeryFragment.kt
Labels: FIX

#254 [FEAT] Change Back Color when state is drag (#253)
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyAdapter.kt
Labels: FEAT, HYEIN💛

#264 [FIX] # 257 ContentsSimple뷰에 웹뷰 변경사항 바로 적용
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
Labels: FIX, YUBIN💙

#269 [FIX] #268 시간형식 변경 함수 중복 적용 문제 해결
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
Labels: FIX, YUBIN💙

#273 [FIX] 검색화면 이미지와 텍스트 변경 오류 및 폰트 지정 (#272)
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/res/layout/activity_search.xml
Labels: FIX, NAYOUNG💜

#275 Feature/webview
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/web/HavitBroadcastReceiver.kt
  app/src/main/java/org/sopt/havit/ui/web/SeesionHelper.kt
  app/src/main/java/org/sopt/havit/ui/web/WebFragment.kt
  app/src/main/res/layout/activity_web.xml
  app/src/main/res/layout/fragment_web.xml
  app/src/main/res/layout/view_custom_web.xml
Labels: FIX, NAYOUNG💜

#277 [FEAT] 마이페이지 서버 api 연동하기 (#276)
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/data/repository/MyPageRepository.kt
  app/src/main/java/org/sopt/havit/domain/repository/MyPageRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, NAYOUNG💜

#284 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryFragment.kt
Labels: FEAT, HYORIM😎

#288 [FIX] #287 시간 형식 중복 변경 문제 해결
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeRecentContentsRvAdapter.kt
Labels: FIX, YUBIN💙

#292 [ENHANCEMENT] 메인바텀뷰 코드 개선 (#291)
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
Labels: NAYOUNG💜, enhancement

#297 [ENHANCEMENT] 마이페이지 xml 마진과 아이디 수정 (#296)
  app/src/main/res/layout/fragment_my_page.xml
Labels: NAYOUNG💜, enhancement

#301 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/SelectCategoryFragment.kt
  app/src/main/res/drawable/rectangle_black_radius_24.xml
  app/src/main/res/layout/toast_max_category.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎

#303 [UI] 유효하지 않은 url에 대한 Toast 추가 (#302)
  app/src/main/res/layout/toast_url_unavailable.xml
  app/src/main/res/values/strings.xml
Labels: UI, HYORIM😎

#306 Feature/share
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/activity_category_content_modify.xml
  app/src/main/res/layout/fragment_category_icon.xml
  app/src/main/res/layout/fragment_choose_icon.xml
  app/src/main/res/layout/item_category_icon.xml
Labels: FIX, UI, HYORIM😎

#314 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryFragment.kt
  app/src/main/java/org/sopt/havit/util/KeyBoardUtil.kt
Labels: FEAT, HYORIM😎

#322 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/EditTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/IconAdapter.kt
  app/src/main/res/layout/fragment_add_category.xml
  app/src/main/res/layout/fragment_choose_icon.xml
  app/src/main/res/layout/fragment_contents_summery.xml
  app/src/main/res/layout/item_category_icon.xml
  app/src/main/res/layout/item_category_selectable.xml
  app/src/main/res/navigation/nav_share.xml
  app/src/main/res/values/strings.xml
Labels: UI, HYORIM😎

#333 Feat/contents
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryDeleteResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryModifyResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryOrderResponse.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
Labels: FEAT, REFACTOR, HYEIN💛

#343 Feature/notification
  .gitignore
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/MyFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/ui/share/ChooseIconFragment.kt
Labels: CHORE, HYORIM😎

#339 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/res/layout/activity_category_order_modify.xml
  app/src/main/res/layout/activity_contents.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_contents_more.xml
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/layout/item_contents_linear_min.xml
Labels: UI, HYEIN💛

#313 Feature/save
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/MainApplication.kt
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/java/org/sopt/havit/util/CustomToast.kt
  app/src/main/java/org/sopt/havit/util/KeyBoardHeightProvider.kt
  app/src/main/res/layout/fragment_save.xml
  app/src/main/res/layout/toast_text.xml
  build.gradle
Labels: FEAT, REFACTOR, NAYOUNG💜

#346 Feat/contents
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/layout/item_contents_linear_min.xml
  app/src/main/res/layout/toast_havit_complete.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, UI, HYEIN💛
