Repository TeamHavit/Havit-Android, pull requests merged in 2022-07, with the labels that each got.

#626 [CHORE] 알림 수정 연동 코드 삭제 (#622)
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ModifyNotificationParams.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreViewModel.kt
Labels: CHORE, HYORIM😎

#627 ToastUtil 생성
  app/src/main/java/org/sopt/havit/ui/category/CategoryAddActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationActivity.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/add_category/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/notification/PickerFragment.kt
  app/src/main/java/org/sopt/havit/util/CustomToast.kt
  app/src/main/java/org/sopt/havit/util/ToastUtil.kt
  app/src/main/res/drawable-hdpi/ic_alarm_white.png
  app/src/main/res/drawable-mdpi/ic_alarm_white.png
  app/src/main/res/drawable-xhdpi/ic_alarm_white.png
  app/src/main/res/drawable-xxhdpi/ic_alarm_white.png
  app/src/main/res/drawable-xxxhdpi/ic_alarm_white.png
  app/src/main/res/layout/fragment_set_notification.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/layout/toast_category_added.xml
  app/src/main/res/layout/toast_set_alarm_complete.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎

#632 Feature/home
  app/src/main/java/org/sopt/havit/data/remote/ContentsSimpleResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/NotificationResponse.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationActivity.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationRvAdapter.kt
  app/src/main/java/org/sopt/havit/util/CalenderUtil.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_contents_simple.xml
  app/src/main/res/layout/item_notification.xml
Labels: FIX, UI, YUBIN💙

#620 [FEAT] 카테고리 수정 시에만 다이얼로그 표시 & 카테고리 서버 실패 처리
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYEIN💛

#633 Feature/setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/ServiceGuideActivity.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationActivity.kt
  app/src/main/java/org/sopt/havit/ui/notification/NotificationViewModel.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/res/drawable-hdpi/img_onboarding_1.png
  app/src/main/res/drawable-mdpi/img_onboarding_1.png
  app/src/main/res/drawable-xhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_1.png
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_service_guide.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/toast_contents_removed.xml
  app/src/main/res/values/strings.xml
Labels: FIX, FEAT, UI, YUBIN💙

#640 [FIX] 온보딩 건너뛰기 텍스트 터치영역 조정
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_fifth.xml
  app/src/main/res/layout/fragment_onboarding_first.xml
  app/src/main/res/layout/fragment_onboarding_fourth.xml
  app/src/main/res/layout/fragment_onboarding_second.xml
  app/src/main/res/layout/fragment_onboarding_third.xml
Labels: FIX, HYEIN💛

#643 Feature/share
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/FirebaseTokenManager.kt
  app/src/main/java/org/sopt/havit/MyFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/FcmTokenParams.kt
  app/src/main/java/org/sopt/havit/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingUnregisterActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInViewModel.kt
Labels: FEAT, HYORIM😎

#645 [FEAT] 컨텐츠 더보기 - 콘텐츠 알림 수정 (#644)
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/ModifyContentNotificationParams.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_notification/EditNotificationFromMoreViewModel.kt
Labels: FEAT, HYORIM😎

#647 [UI] 환경설정 / 약관 및 정책 - 부칙(시행일) 명시되어 있는 이미지로 교체 (#646)
  app/src/main/res/drawable/img_privacy_policy.png
Labels: UI, HYORIM😎

#648 [CHORE] 환경설정 / 생명주기 변경 -> 수정된 닉네임 즉각 반영
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
Labels: CHORE, HYORIM😎

#652 Feature/login
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingUnregisterActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/AddNickNameFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/AddTosFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/layout/activity_splash_with_sign.xml
  app/src/main/res/layout/fragment_add_nick_name.xml
  app/src/main/res/layout/fragment_add_tos.xml
  app/src/main/res/values/themes.xml
Labels: FIX, FEAT, NAYOUNG💜
