Repository TeamHavit/Havit-Android, pull requests merged in 2022-06, with the labels that each got.

#593 [FEAT] 공유프로세스 로그인 분기처리 (#592)
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
Labels: FEAT, HYORIM😎

#597 Feature/share
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignInViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/anim/alpha_0_to_100_1500_delay_1000.xml
  app/src/main/res/anim/alpha_15_to_5_20000.xml
  app/src/main/res/anim/alpha_invisible_to_visible_1500.xml
  app/src/main/res/anim/alpha_invisible_to_visible_2000.xml
  app/src/main/res/drawable-hdpi/ic_splash.png
  app/src/main/res/drawable-mdpi/ic_splash.png
  app/src/main/res/drawable-xhdpi/ic_splash.png
  app/src/main/res/drawable-xxhdpi/ic_splash.png
  app/src/main/res/drawable-xxxhdpi/ic_splash.png
  app/src/main/res/layout/activity_splash_with_sign.xml
  app/src/main/res/values/themes.xml
Labels: FEAT, UI, HYORIM😎

#603 Feature/modify category
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/mapper/CategoryMapper.kt
  app/src/main/java/org/sopt/havit/data/remote/AllCategoryResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/ModifyContentCategoryParams.kt
  app/src/main/java/org/sopt/havit/domain/entity/Category.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/BottomSheetMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_title/EditTitleFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_edit_category_from_more.xml
  app/src/main/res/layout/item_category_toggle.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎

#608 [FIX] splashwithsignactivity 백스택 제거
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
Labels: FIX, NAYOUNG💜

#607 Feature/save
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/res/layout/fragment_save.xml
Labels: FIX, NAYOUNG💜

#610 Feature/setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/local/HavitAuthLocalPreferences.kt
  app/src/main/java/org/sopt/havit/data/remote/NewNicknameRequest.kt
  app/src/main/java/org/sopt/havit/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/source/local/AuthLocalDataSource.kt
  app/src/main/java/org/sopt/havit/data/source/local/AuthLocalDataSourceImpl.kt
  app/src/main/java/org/sopt/havit/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingModifyNicknameActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingUnregisterActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/org/sopt/havit/util/DialogOkUtil.kt
  app/src/main/java/org/sopt/havit/util/MySharedPreference.kt
  app/src/main/res/drawable-hdpi/ic_active_check_circle.png
  app/src/main/res/drawable-mdpi/ic_active_check_circle.png
  app/src/main/res/drawable-xhdpi/ic_active_check_circle.png
  app/src/main/res/drawable-xxhdpi/ic_active_check_circle.png
  app/src/main/res/drawable-xxxhdpi/ic_active_check_circle.png
  app/src/main/res/drawable/rectangle_havit_gray_bottom_radius_8.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_setting_modify_nickname.xml
  app/src/main/res/layout/activity_setting_unregister.xml
  app/src/main/res/layout/dialog_ok_util.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, REFACTOR, UI, YUBIN💙
