Repository TeamHavit/Havit-Android, pull requests merged in 2022-09, with the labels that each got.

#707 Feat/category
  app/build.gradle
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/mapper/CategoryMapper.kt
  app/src/main/java/org/sopt/havit/data/remote/AllCategoryResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/UpdateCategoriesOrderRequest.kt
  app/src/main/java/org/sopt/havit/data/remote/UpdateCategoryInfoRequest.kt
  app/src/main/java/org/sopt/havit/data/repository/CategoryRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/source/remote/category/CategoryRemoteDataSource.kt
  app/src/main/java/org/sopt/havit/data/source/remote/category/CategoryRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/havit/di/DataSourceModule.kt
  app/src/main/java/org/sopt/havit/di/RepositoryModule.kt
  app/src/main/java/org/sopt/havit/domain/entity/Category.kt
  app/src/main/java/org/sopt/havit/domain/entity/CategoryWithSelected.kt
  app/src/main/java/org/sopt/havit/domain/repository/CategoryRepository.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyAdapter.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsCategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryAllActivity.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryRvAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeCategoryVpAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/havit/ui/mypage/ContentsFromMyPageActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/add_category/EnterCategoryTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_category_modify.xml
  app/src/main/res/layout/item_category_toggle.xml
  app/src/main/res/layout/item_dialog_contents_top.xml
  app/src/main/res/layout/item_home_category_list.xml
Labels: FEAT, REFACTOR, HYEIN💛

#710 [FEAT] 이벤트, 광고성 수신마케팅 동의 수집하여 signup api에 추가 (#709)
  app/src/main/java/org/sopt/havit/data/remote/SignUpRequest.kt
  app/src/main/java/org/sopt/havit/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/source/remote/AuthRemoteDataSource.kt
  app/src/main/java/org/sopt/havit/data/source/remote/AuthRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/havit/domain/repository/AuthRepository.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignUpViewModel.kt
Labels: FEAT, NAYOUNG💜

#714 [FEAT] 콘텐츠 뷰 setOnSingleClickListener 적용
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/ContentsMoreFragment.kt
Labels: FEAT, HYEIN💛

#715 [FIX] 실수로 삭제한 코드 as () -> Unit 다시 넣기
  app/src/main/java/org/sopt/havit/ui/contents/more/ContentsMoreFragment.kt
Labels: FIX, HYEIN💛

#718 [FIX] 콘텐츠 뷰 에러 수정
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsCategoryFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
Labels: FIX, HYEIN💛

#723 [FIX] 최초 닉네임 등록시 변경이 안되는 버그 수정 (#722)
  app/src/main/java/org/sopt/havit/ui/sign/SignUpViewModel.kt
Labels: FIX, NAYOUNG💜

#725 [FEAT] 공유프로세스 에러처리 - 최초 진입, 카테고리 선택 뷰
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/CategoryResponse.kt
  app/src/main/java/org/sopt/havit/domain/entity/CategoryWithSelected.kt
  app/src/main/java/org/sopt/havit/domain/model/NetworkStatus.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/EditCategoryFromMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/contents/more/edit_category/SelectableCategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/share/BottomSheetNetworkErrorFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/select_category/CategorySelectableAdapter.kt
  app/src/main/java/org/sopt/havit/ui/share/select_category/SelectCategoryFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_bottom_sheet_network_error.xml
  app/src/main/res/layout/fragment_contents_more.xml
  app/src/main/res/layout/fragment_select_category.xml
  app/src/main/res/layout/layout_bottom_sheet_network_error.xml
  app/src/main/res/layout/layout_share_select_category.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: FEAT, HYORIM😎

#727 Feature/login
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
  app/src/main/res/layout/activity_splash_with_sign.xml
Labels: FIX, UI, NAYOUNG💜

#728 [FEAT] 카테고리 추가 뷰 에러처리
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/add_category/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/add_category/EnterCategoryTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/res/layout/fragment_enter_category_title.xml
Labels: FEAT, HYORIM😎

#729 [FEAT] 카테고리추가-아이콘선택 / 에러뷰 처리
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/add_category/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/select_category/SelectCategoryFragment.kt
  app/src/main/res/layout/fragment_choose_icon.xml
  app/src/main/res/layout/fragment_enter_category_title.xml
Labels: FEAT, HYORIM😎

#730 [FEAT] 공유프로세스 - 카테고리 선택 뷰 스켈레톤 작업
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/select_category/SelectCategoryFragment.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/item_category_toggle.xml
  app/src/main/res/layout/layout_category_list_skeleton.xml
  app/src/main/res/layout/layout_share_select_category.xml
Labels: FEAT, HYORIM😎

#733 [FEAT] 서버 에러 화면 refresh icon 애니메이션 추가 (#732)
  app/src/main/java/org/sopt/havit/ui/sign/AddTosFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
Labels: FEAT, NAYOUNG💜

#734 [FEAT] 서버 에러 화면 refresh icon 애니메이션 추가 (#732)
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
Labels: FEAT, NAYOUNG💜

#735 [FEAT] webView 서버 에러 처리 구현 및 refresh 애니메이션 추가 (#732)
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
  app/src/main/res/layout/activity_web.xml
Labels: FEAT, NAYOUNG💜

#737 [UI] 폰트스타일 sp에서 dp로 변경 (#724)
  app/src/main/res/values/themes.xml
Labels: UI, YUBIN💙

#739 Feat/fcm
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/HavitFirebaseMessagingService.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
Labels: FIX, HYORIM😎

#741 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/add_category/EnterCategoryTitleFragment.kt
Labels: FEAT, HYORIM😎

#743 Feature/setting
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/domain/entity/Notice.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingNoticeActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/adapter/NoticeAdapter.kt
  app/src/main/java/org/sopt/havit/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/res/layout/activity_setting_notice.xml
  app/src/main/res/layout/item_notice.xml
Labels: FEAT, HYORIM😎

#745 [FIX] 공유 프로세스 키보드와 다음 버튼 간격 수정하기 (#731)
  app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
  app/src/main/res/layout/fragment_save.xml
Labels: FIX, NAYOUNG💜

#748 [FIX] API 버전 28이하에서 나타나는 selector 오류 해결
  app/src/main/java/org/sopt/havit/ui/contents/DialogContentsCategoryFragment.kt
  app/src/main/res/color/selector_contents_category_dialog_background.xml
  app/src/main/res/color/selector_contents_order.xml
  app/src/main/res/drawable/rectangle_purple_category.xml
  app/src/main/res/drawable/rectangle_white.xml
  app/src/main/res/drawable/selector_contents_order.xml
  app/src/main/res/layout/fragment_dialog_contents_filter.xml
  app/src/main/res/layout/item_dialog_contents_top.xml
Labels: FIX, HYEIN💛

#749 Feature/share
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
Labels: CHORE, HYORIM😎

#751 [CHORE] 백버튼 처리
  app/src/main/java/org/sopt/havit/ui/setting/SettingNoticeActivity.kt
Labels: CHORE, HYORIM😎

#753 [FIX] HomeFragment / 뷰 재진입 시 StickyHeader Y Position 위치 오류 (#752)
  app/src/main/java/org/sopt/havit/util/StickyScrollView.kt
Labels: FIX, HYORIM😎

#755 [FIX] HomeFragment / 스크롤 민감도 조정
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/util/ViewPager2Extension.kt
Labels: FIX, HYORIM😎
