Repository TeamHavit/Havit-Android, pull requests merged in 2023-05, with the labels that each got.

#846 [CHORE] gitignore 수정
  .idea/.gitignore
Labels: CHORE, HYORIM😎

#848 [FIX] 회원탈퇴 중복 요청 방지 (#840)
  app/src/main/java/org/sopt/havit/util/DialogOkUtil.kt
Labels: FIX, HYORIM😎

#851 [FIX] isCategoryNameAlreadyExist 함수 stream 사용 부분 수정 (#841)
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryViewModel.kt
Labels: FIX, HYORIM😎

#847 [UI] BindingAdapter - imageUrl의 placeholder 더미이미지 변경 (#839)
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/values/styles.xml
Labels: UI, HYORIM😎

#843 [FIX] 닉네임 생성시 띄어쓰기 되지 않도록 설정 (#842)
  app/src/main/java/org/sopt/havit/ui/sign/AddNickNameFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/NickNameTextStatus.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignUpViewModel.kt
  app/src/main/res/layout/fragment_add_nick_name.xml
  app/src/main/res/values/strings.xml
Labels: FIX, NAYOUNG💜

#852 [FEAT] 환경설정 > 버전정보 뷰 추가 #849
  app/build.gradle
  app/src/main/java/org/sopt/havit/domain/entity/VersionState.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎

#857 [RELEASE] v1.0.6 배포완료
  .idea/.gitignore
  app/build.gradle
  app/src/main/java/org/sopt/havit/domain/entity/VersionState.kt
  app/src/main/java/org/sopt/havit/ui/setting/SettingActivity.kt
  app/src/main/java/org/sopt/havit/ui/setting/viewmodel/SettingViewModel.kt
  app/src/main/java/org/sopt/havit/ui/share/AddCategoryViewModel.kt
  app/src/main/java/org/sopt/havit/ui/sign/AddNickNameFragment.kt
  app/src/main/java/org/sopt/havit/ui/sign/NickNameTextStatus.kt
  app/src/main/java/org/sopt/havit/ui/sign/SignUpViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/java/org/sopt/havit/util/DialogOkUtil.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_add_nick_name.xml
  app/src/main/res/layout/item_contents_grid.xml
  app/src/main/res/layout/item_contents_linear_max.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: HYORIM😎, 🎉RELEASE🎉

#862 [FIX] icon_setting padding 8dp 설정(#853)
  app/src/main/res/layout/fragment_my_page.xml
Labels: FIX, NAYOUNG💜

#864 [REFACTOR] 콘텐츠 저장 프로세스 코드 개선 (#863)
  app/src/main/java/org/sopt/havit/ui/contents/more/ContentsMoreFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/util/HavitSharedPreference.kt
  app/src/main/res/layout/activity_share.xml
Labels: REFACTOR, HYORIM😎

#859 [FEAT] Android O SplashWithSignActivity Orientation fix (#858)
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/category/CategoryAddActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/sign/SplashWithSignActivity.kt
Labels: FIX, NAYOUNG💜

#861 [FIX] string.xml app_key 제거 (#860)
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: FIX, NAYOUNG💜

#868 [REFACTOR] intent key값 상수로 전환 & 필요없는 intent data 삭제 (#867)
  app/src/main/java/org/sopt/havit/ui/category/CategoryContentModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryOrderModifyActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
Labels: REFACTOR, HYEIN💛

#869 [FIX] 카테고리 화면 -> 콘텐츠 화면 진입 후 해당 카테고리 수정 시 index error 해결 (#866)
  app/src/main/java/org/sopt/havit/domain/entity/Category.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryAdapter.kt
Labels: FIX, HYEIN💛
