Repository TeamHavit/Havit-Android, pull requests merged in 2023-04, with the labels that each got.

#824 [FEAT] ga_util 함수 작성 및 적용 (#823)
  app/src/main/java/org/sopt/havit/ui/contents/ContentsActivity.kt
  app/src/main/java/org/sopt/havit/ui/contents/ContentsViewModel.kt
  app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchActivity.kt
  app/src/main/java/org/sopt/havit/ui/search/SearchViewModel.kt
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/ui/web/WebViewModel.kt
  app/src/main/java/org/sopt/havit/util/GoogleAnalyticsUtil.kt
Labels: FEAT

#827 [FEAT] home 화면에 있는 이벤트 GA 붙이기
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/ui/home/HomeFragment.kt
  app/src/main/java/org/sopt/havit/util/GoogleAnalyticsUtil.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_picker.xml
Labels: FEAT, HYEIN💛

#829 Feat/ga save
  app/src/main/java/org/sopt/havit/ui/share/add_category/ChooseIconFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/add_category/EnterCategoryTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/contents_summery/ContentsSummeryFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/edit_title/EditTitleFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/notification/SetNotificationFragment.kt
  app/src/main/java/org/sopt/havit/ui/share/select_category/SelectCategoryFragment.kt
  app/src/main/java/org/sopt/havit/util/GoogleAnalyticsUtil.kt
Labels: FEAT, HYORIM😎

#831 [FIX] 추천사이트 웹뷰에서 공유하기 영역 활성화 (#830)
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/res/layout/activity_web.xml
Labels: FIX, NAYOUNG💜

#833 [FIX] durationTime 타입 변경 및 적용 함수 구현 (#832)
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
  app/src/main/java/org/sopt/havit/util/GoogleAnalyticsUtil.kt
Labels: FIX, NAYOUNG💜

#838 [FEAT] Crashlytics plugin 추가 (#837)
  app/build.gradle
  build.gradle
Labels: FEAT, HYORIM😎
