Repository TeamHavit/Havit-Android, pull requests merged in 2024-05, with the labels that each got.

#926 [UI] 설정 화면 하단의 해빗 제작자 팀원 소속(AOS->Server) 변경
  app/src/main/res/layout/activity_setting.xml
Labels: UI, HYEIN💛

#928 [UI] 커뮤니티 글 작성 UI구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/ui/community/CreatePostActivity.kt
  app/src/main/java/org/sopt/havit/ui/community/CreatePostViewModel.kt
  app/src/main/java/org/sopt/havit/ui/model/CommunityCategoryRO.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/java/org/sopt/havit/util/HavitChipGroup.kt
  app/src/main/java/org/sopt/havit/util/havit_edit_text/EditTextData.kt
  app/src/main/java/org/sopt/havit/util/havit_edit_text/EditTextInfoType.kt
  app/src/main/java/org/sopt/havit/util/havit_edit_text/HavitEditText.kt
  app/src/main/res/layout/activity_create_post.xml
  app/src/main/res/layout/layout_havit_edit_text.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: UI, HYORIM😎

#930 [FEAT] 커뮤니티 글 등록 중 뒤로가기 감지 시 '글 작성 취소' 다이얼로그 표시 (#929)
  app/src/main/java/org/sopt/havit/ui/community/CreatePostActivity.kt
  app/src/main/java/org/sopt/havit/ui/community/CreatePostViewModel.kt
  app/src/main/java/org/sopt/havit/ui/home/community/CommunityFragment.kt
  app/src/main/java/org/sopt/havit/util/DialogUtil.kt
  app/src/main/res/layout/activity_create_post.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYORIM😎

#933 [REFACTOR] CategoryList 업데이트 notifyDataSetChanged -> DiffUtil로 변경 (#932)
  app/src/main/java/org/sopt/havit/ui/category/CategoryAdapter.kt
  app/src/main/java/org/sopt/havit/ui/category/CategoryFragment.kt
Labels: REFACTOR, HYEIN💛

#923 [FEAT] 커뮤니티 게시글 조회(전체, 카테고리 별) API & 신고하기 API 연동
  app/build.gradle
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/remote/CommunityPostResponse.kt
  app/src/main/java/org/sopt/havit/data/remote/CommunityReportRequest.kt
  app/src/main/java/org/sopt/havit/data/repository/CommunityRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/source/remote/community/CommunityByCommunityPagingSource.kt
  app/src/main/java/org/sopt/havit/data/source/remote/community/CommunityPagingSource.kt
  app/src/main/java/org/sopt/havit/data/source/remote/community/CommunityRemoteDataSource.kt
  app/src/main/java/org/sopt/havit/data/source/remote/community/CommunityRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/havit/di/DataSourceModule.kt
  app/src/main/java/org/sopt/havit/di/RepositoryModule.kt
  app/src/main/java/org/sopt/havit/domain/entity/CommunityPost.kt
  app/src/main/java/org/sopt/havit/domain/repository/CommunityRepository.kt
  app/src/main/java/org/sopt/havit/ui/home/community/BottomSheetReportFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/community/CommunityFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/community/CommunityPagingDataAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/community/CommunityViewModel.kt
  app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_bottom_sheet_report.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/item_community.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, HYEIN💛

#921 [FIX] 웹뷰에서 외부 앱 열기 클릭시 딥링크 에러 핸들링
  app/src/main/java/org/sopt/havit/ui/web/WebActivity.kt
Labels: FIX, NAYOUNG💜

#935 [FEAT] 신기능(커뮤니티) 초기 알림 다이얼로그 제작
  app/src/main/java/org/sopt/havit/ui/home/BottomSheetNoticeCommunityFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/MainHomeFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/MainHomeViewModel.kt
  app/src/main/java/org/sopt/havit/util/HavitSharedPreference.kt
  app/src/main/res/drawable-hdpi/img_notice_community.jpg
  app/src/main/res/drawable-mdpi/img_notice_community.jpg
  app/src/main/res/drawable-xhdpi/img_notice_community.jpg
  app/src/main/res/drawable-xxhdpi/img_notice_community.jpg
  app/src/main/res/drawable-xxxhdpi/img_notice_community.jpg
  app/src/main/res/drawable/rectangle_havit_purple_radius_5.xml
  app/src/main/res/layout/fragment_bottom_sheet_notice_community.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: FEAT, HYEIN💛

#936 Feature/community detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/havit/data/api/HavitApi.kt
  app/src/main/java/org/sopt/havit/data/repository/CommunityRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/source/remote/community/CommunityRemoteDataSource.kt
  app/src/main/java/org/sopt/havit/data/source/remote/community/CommunityRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/havit/domain/entity/CommunityPost.kt
  app/src/main/java/org/sopt/havit/domain/repository/CommunityRepository.kt
  app/src/main/java/org/sopt/havit/ui/community/CommunityDetailActivity.kt
  app/src/main/java/org/sopt/havit/ui/community/CommunityDetailViewModel.kt
  app/src/main/java/org/sopt/havit/util/ToastUtil.kt
  app/src/main/res/drawable-hdpi/img_profile.png
  app/src/main/res/drawable-mdpi/img_profile.png
  app/src/main/res/drawable-xhdpi/img_profile.png
  app/src/main/res/drawable-xxhdpi/img_profile.png
  app/src/main/res/drawable-xxxhdpi/img_profile.png
  app/src/main/res/drawable/rectangle_white_gray_light_radius_5.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, NAYOUNG💜

#938 [FEAT] 커뮤니티 홈화면에서 신고하기 시 데이터 갱신하는 로직 추가
  app/src/main/java/org/sopt/havit/ui/home/community/CommunityFragment.kt
  app/src/main/java/org/sopt/havit/ui/home/community/CommunityPagingDataAdapter.kt
  app/src/main/java/org/sopt/havit/ui/home/community/CommunityViewModel.kt
Labels: FEAT, HYEIN💛

#942 [FIX] 커뮤니티 상세 화면에서 콘텐츠 저장이 제대로 안되는 이슈 해결 (#941)
  app/src/main/java/org/sopt/havit/MainActivity.kt
  app/src/main/java/org/sopt/havit/data/remote/OgData.kt
  app/src/main/java/org/sopt/havit/data/repository/UrlRepositoryImpl.kt
  app/src/main/java/org/sopt/havit/data/source/remote/url/UrlDataSourceImpl.kt
  app/src/main/java/org/sopt/havit/di/UseCaseModule.kt
  app/src/main/java/org/sopt/havit/domain/repository/UrlRepository.kt
  app/src/main/java/org/sopt/havit/domain/usecase/LoadOgDataUseCase.kt
  app/src/main/java/org/sopt/havit/domain/usecase/UrlUseCase.kt
  app/src/main/java/org/sopt/havit/ui/community/CreatePostViewModel.kt
  app/src/main/java/org/sopt/havit/ui/contents_simple/ContentsSimpleActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareActivity.kt
  app/src/main/java/org/sopt/havit/ui/share/ShareViewModel.kt
Labels: FIX, HYORIM😎
